// ============================================
// images.js — Image upload & forensic scan
// ============================================

const uploadZone     = document.getElementById('uploadZone');
const fileInput      = document.getElementById('fileInput');
const imageResult    = document.getElementById('imageResult');
const imagePreview   = document.getElementById('imagePreview');
const imgResultLabel = document.getElementById('imgResultLabel');
const imgResultDetail= document.getElementById('imgResultDetail');
const metricAuth     = document.getElementById('metricAuth');
const metricMeta     = document.getElementById('metricMeta');
const metricCompress = document.getElementById('metricCompress');

// ── Drag-and-drop ──
uploadZone.addEventListener('dragover', (e) => {
  e.preventDefault();
  uploadZone.classList.add('drag-over');
});
uploadZone.addEventListener('dragleave', () => {
  uploadZone.classList.remove('drag-over');
});
uploadZone.addEventListener('drop', (e) => {
  e.preventDefault();
  uploadZone.classList.remove('drag-over');
  const file = e.dataTransfer.files[0];
  if (file && file.type.startsWith('image/')) {
    processImage(file);
  }
});

// ── File input change ──
fileInput.addEventListener('change', (e) => {
  const file = e.target.files[0];
  if (file) processImage(file);
});

// ── Read and preview the image ──
function processImage(file) {
  const reader = new FileReader();
  reader.onload = (e) => {
    imagePreview.src = e.target.result;
    // If you have a real backend endpoint, replace simulateImageScan() with:
    // await sendImageToBackend(file);
    simulateImageScan();
  };
  reader.readAsDataURL(file);
}

// ── Simulated scan (replace with real API call when ready) ──
function simulateImageScan() {
  imageResult.style.display = 'block';
  imageResult.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

  const authScore  = Math.round(Math.random() * 40 + 55);
  const metaOk     = Math.random() > 0.4;
  const compScore  = Math.round(Math.random() * 30 + 60);
  const isSuspect  = authScore < 70;

  imgResultLabel.textContent = isSuspect
    ? '🚨 Possible Manipulation Detected'
    : '✅ Image Appears Authentic';
  imgResultLabel.style.color = isSuspect ? 'var(--pink)' : '#4ade80';

  imgResultDetail.textContent = isSuspect
    ? 'Our forensic engine detected potential pixel-level inconsistencies. This image may have been altered or generated by AI.'
    : 'No significant manipulation artifacts detected. Metadata and compression patterns appear consistent with a genuine photograph.';

  metricAuth.textContent          = authScore + '%';
  metricAuth.style.color          = authScore >= 70 ? '#4ade80' : 'var(--pink)';

  metricMeta.textContent          = metaOk ? 'OK' : 'MISSING';
  metricMeta.style.color          = metaOk ? '#4ade80' : 'var(--pink)';

  metricCompress.textContent      = compScore + '%';
  metricCompress.style.color      = compScore >= 70 ? '#4ade80' : 'var(--purple)';
}

// ── Real backend stub (uncomment & implement when ready) ──
/*
async function sendImageToBackend(file) {
  const formData = new FormData();
  formData.append('image', file);

  try {
    const res  = await fetch('http://localhost:5000/predict-image', { method: 'POST', body: formData });
    const data = await res.json();
    // Use data.authenticity, data.metadata_ok, data.compression_score etc.
  } catch (err) {
    imgResultLabel.textContent = '⚠️ Could not connect to backend.';
    imgResultLabel.style.color = '#fbbf24';
    imageResult.style.display  = 'block';
  }
}
*/

console.log('images.js loaded');
